export const openLayersCategories = [
  {
    id: 3000,
    name: "OpenLayers案例",
    icon: "🧩",
    count: 0,
    subcategories: [
      { id: 3001, name: "地图与图层", count: 0, parentId: 3000 },
      { id: 3002, name: "交互与工具", count: 0, parentId: 3000 },
      { id: 3003, name: "样式与可视化", count: 0, parentId: 3000 },
      { id: 3004, name: "动画与追踪", count: 0, parentId: 3000 },
      { id: 3005, name: "WebGL 渲染", count: 0, parentId: 3000 },
      { id: 3006, name: "风场模拟", count: 0, parentId: 3000 },
      { id: 3007, name: "区域与分析", count: 0, parentId: 3000 },
      { id: 3008, name: "数据加载", count: 0, parentId: 3000 },
    ],
  },
];

export const openLayersExamples = [
  {
    id: "01_国内底图",
    name: "国内底图",
    fileName: "openLayersExample/01_国内底图.vue",
    category: 3001,
    preview: "@/assets/openlayersImg/01_国内底图.png",
  },
  {
    id: "100_切换图层",
    name: "切换图层",
    fileName: "openLayersExample/100_切换图层.vue",
    category: 3001,
    preview: "@/assets/openlayersImg/100_切换图层.png",
  },
  {
    id: "111_墨绿色底图",
    name: "墨绿色底图",
    fileName: "openLayersExample/111_墨绿色底图.vue",
    category: 3001,
    preview: "@/assets/openlayersImg/111_墨绿色底图.png",
  },
  {
    id: "113_底图颜色调节",
    name: "底图颜色调节",
    fileName: "openLayersExample/113_底图颜色调节.vue",
    category: 3001,
    preview: "@/assets/openlayersImg/113_底图颜色调节.png",
  },
  {
    id: "123_图层裁剪",
    name: "图层裁剪",
    fileName: "openLayersExample/123_图层裁剪.vue",
    category: 3001,
    preview: "@/assets/openlayersImg/123_图层裁剪.png",
  },
  {
    id: "116_瓦片坐标与经纬网",
    name: "瓦片坐标与经纬网",
    fileName: "openLayersExample/116_瓦片坐标与经纬网.vue",
    category: 3001,
    preview: "@/assets/openlayersImg/116_瓦片坐标与经纬网.png",
  },
  {
    id: "02_气泡窗口",
    name: "气泡窗口",
    fileName: "openLayersExample/02_气泡窗口.vue",
    category: 3002,
    preview: "@/assets/openlayersImg/02_气泡窗口.png",
  },
  {
    id: "03_Geojson",
    name: "Geojson",
    fileName: "openLayersExample/03_Geojson.vue",
    category: 3002,
    preview: "@/assets/openlayersImg/03_Geojson.png",
  },
  {
    id: "102_绘制",
    name: "绘制",
    fileName: "openLayersExample/102_绘制.vue",
    category: 3002,
    preview: "@/assets/openlayersImg/102_绘制.png",
  },
  {
    id: "122_长度面积计算",
    name: "长度面积计算",
    fileName: "openLayersExample/122_长度面积计算.vue",
    category: 3007,
    preview: "@/assets/openlayersImg/122_长度面积计算.png",
  },
  {
    id: "127_导出PNG",
    name: "导出PNG",
    fileName: "openLayersExample/127_导出PNG.vue",
    category: 3002,
    preview: "@/assets/openlayersImg/127_导出PNG.png",
  },
  {
    id: "128_图层望远镜",
    name: "图层望远镜",
    fileName: "openLayersExample/128_图层望远镜.vue",
    category: 3002,
    preview: "@/assets/openlayersImg/128_图层望远镜.png",
  },
  {
    id: "129_图层放大",
    name: "图层放大",
    fileName: "openLayersExample/129_图层放大.vue",
    category: 3002,
    preview: "@/assets/openlayersImg/129_图层放大.png",
  },
  {
    id: "121_即时渲染",
    name: "即时渲染",
    fileName: "openLayersExample/121_即时渲染.vue",
    category: 3002,
    preview: "@/assets/openlayersImg/121_即时渲染.png",
  },
  {
    id: "132_共享视图",
    name: "共享视图",
    fileName: "openLayersExample/132_共享视图.vue",
    category: 3002,
    preview: "@/assets/openlayersImg/132_共享视图.png",
  },
  {
    id: "104_热力图",
    name: "热力图",
    fileName: "openLayersExample/104_热力图.vue",
    category: 3003,
    preview: "@/assets/openlayersImg/104_热力图.png",
  },
  {
    id: "101_点位聚合",
    name: "点位聚合",
    fileName: "openLayersExample/101_点位聚合.vue",
    category: 3003,
    preview: "@/assets/openlayersImg/101_点位聚合.png",
  },
  {
    id: "108_动态闪烁",
    name: "动态闪烁",
    fileName: "openLayersExample/108_动态闪烁.vue",
    category: 3003,
    preview: "@/assets/openlayersImg/108_动态闪烁.png",
  },
  {
    id: "109_分屏对比",
    name: "分屏对比",
    fileName: "openLayersExample/109_分屏对比.vue",
    category: 3003,
    preview: "@/assets/openlayersImg/109_分屏对比.png",
  },
  {
    id: "110_ol-echarts",
    name: "ol-echarts",
    fileName: "openLayersExample/110_ol-echarts.vue",
    category: 3003,
    preview: "@/assets/openlayersImg/110_ol-echarts.png",
  },
  {
    id: "119_动态数据",
    name: "动态数据",
    fileName: "openLayersExample/119_动态数据.vue",
    category: 3003,
    preview: "@/assets/openlayersImg/119_动态数据.png",
  },
  {
    id: "131_文本碰撞检测",
    name: "文本碰撞检测",
    fileName: "openLayersExample/131_文本碰撞检测.vue",
    category: 3003,
    preview: "@/assets/openlayersImg/131_文本碰撞检测.png",
  },
  {
    id: "133_沿线文本",
    name: "沿线文本",
    fileName: "openLayersExample/133_沿线文本.vue",
    category: 3003,
    preview: "@/assets/openlayersImg/133_沿线文本.png",
  },
  {
    id: "134_平滑算法",
    name: "平滑算法",
    fileName: "openLayersExample/134_平滑算法.vue",
    category: 3007,
    preview: "@/assets/openlayersImg/134_平滑算法.png",
  },
  {
    id: "130_自定义形状",
    name: "自定义形状",
    fileName: "openLayersExample/130_自定义形状.vue",
    category: 3003,
    preview: "@/assets/openlayersImg/130_自定义形状.png",
  },
  {
    id: "117_添加顶点样式",
    name: "添加顶点样式",
    fileName: "openLayersExample/117_添加顶点样式.vue",
    category: 3003,
    preview: "@/assets/openlayersImg/117_添加顶点样式.png",
  },
  {
    id: "118_绘制五角星",
    name: "绘制五角星",
    fileName: "openLayersExample/118_绘制五角星.vue",
    category: 3003,
    preview: "@/assets/openlayersImg/118_绘制五角星.png",
  },
  {
    id: "103_轨迹回放",
    name: "轨迹回放",
    fileName: "openLayersExample/103_轨迹回放.vue",
    category: 3004,
    preview: "@/assets/openlayersImg/103_轨迹回放.png",
  },
  {
    id: "135_追踪要素",
    name: "追踪要素",
    fileName: "openLayersExample/135_追踪要素.vue",
    category: 3004,
    preview: "@/assets/openlayersImg/135_追踪要素.png",
  },
  {
    id: "125_绘制箭头线",
    name: "绘制箭头线",
    fileName: "openLayersExample/125_绘制箭头线.vue",
    category: 3003,
    preview: "@/assets/openlayersImg/125_绘制箭头线.png",
  },
  {
    id: "115_加载gif图",
    name: "加载gif图",
    fileName: "openLayersExample/115_加载gif图.vue",
    category: 3008,
    preview: "@/assets/openlayersImg/115_加载gif图.png",
  },
  {
    id: "136_webgl渲染海量点位",
    name: "webgl渲染海量点位",
    fileName: "openLayersExample/136_webgl渲染海量点位.vue",
    category: 3005,
    preview: "@/assets/openlayersImg/136_webgl渲染海量点位.png",
  },
  {
    id: "137_webgl渲染精灵图",
    name: "webgl渲染精灵图",
    fileName: "openLayersExample/137_webgl渲染精灵图.vue",
    category: 3005,
    preview: "@/assets/openlayersImg/137_webgl渲染精灵图.png",
  },
  {
    id: "139_风场",
    name: "风场",
    fileName: "openLayersExample/139_风场.vue",
    category: 3006,
    preview: "@/assets/openlayersImg/139_风场.png",
  },
  {
    id: "114_模拟台风风场",
    name: "模拟台风风场",
    fileName: "openLayersExample/114_模拟台风风场.vue",
    category: 3006,
    preview: "@/assets/openlayersImg/114_模拟台风风场.png",
  },
  {
    id: "107_区域掩膜",
    name: "区域掩膜",
    fileName: "openLayersExample/107_区域掩膜.vue",
    category: 3007,
    preview: "@/assets/openlayersImg/107_区域掩膜.png",
  },
];
