export const openLayersCategories = [
  {
    id: 3000,
    name: "OpenLayers案例",
    icon: "🧩",
    count: 0,
    subcategories: [
      { id: 3001, name: "地图与图层", count: 0, parentId: 3000 },
      { id: 3002, name: "交互与工具", count: 0, parentId: 3000 },
      { id: 3003, name: "样式与可视化", count: 0, parentId: 3000 },
      { id: 3004, name: "动画与追踪", count: 0, parentId: 3000 },
      { id: 3005, name: "WebGL 渲染", count: 0, parentId: 3000 },
      { id: 3006, name: "风场模拟", count: 0, parentId: 3000 },
      { id: 3007, name: "区域与分析", count: 0, parentId: 3000 },
      { id: 3008, name: "数据加载", count: 0, parentId: 3000 },
    ],
  },
];

export const openLayersExamples = [
  {
    id: "01_国内底图",
    name: "国内底图",
    fileName: "openLayersExample/basic/01_国内底图.vue",
    category: 3001,
  },
  {
    id: "100_切换图层",
    name: "切换图层",
    fileName: "openLayersExample/basic/100_切换图层.vue",
    category: 3001,
  },
  {
    id: "111_墨绿色底图",
    name: "墨绿色底图",
    fileName: "openLayersExample/basic/111_墨绿色底图.vue",
    category: 3001,
  },
  {
    id: "112_官方hcl",
    name: "官方hcl",
    fileName: "openLayersExample/basic/112_官方hcl.vue",
    category: 3001,
  },
  {
    id: "113_底图颜色调节",
    name: "底图颜色调节",
    fileName: "openLayersExample/basic/113_底图颜色调节.vue",
    category: 3001,
  },
  {
    id: "123_图层裁剪",
    name: "图层裁剪",
    fileName: "openLayersExample/basic/123_图层裁剪.vue",
    category: 3001,
  },
  {
    id: "124_图层分辨率",
    name: "图层分辨率",
    fileName: "openLayersExample/basic/124_图层分辨率.vue",
    category: 3001,
  },
  {
    id: "116_瓦片坐标与经纬网",
    name: "瓦片坐标与经纬网",
    fileName: "openLayersExample/basic/116_瓦片坐标与经纬网.vue",
    category: 3001,
  },
  {
    id: "05_控件",
    name: "控件",
    fileName: "openLayersExample/basic/05_控件.vue",
    category: 3002,
  },
  {
    id: "06_interaction交互",
    name: "interaction交互",
    fileName: "openLayersExample/basic/06_interaction交互.vue",
    category: 3002,
  },
  {
    id: "07_overlay",
    name: "overlay",
    fileName: "openLayersExample/basic/07_overlay.vue",
    category: 3002,
  },
  {
    id: "08_定位",
    name: "定位",
    fileName: "openLayersExample/basic/08_定位.vue",
    category: 3002,
  },
  {
    id: "10_DragZoom",
    name: "DragZoom",
    fileName: "openLayersExample/basic/10_DragZoom.vue",
    category: 3002,
  },
  {
    id: "11_Draw",
    name: "Draw",
    fileName: "openLayersExample/basic/11_Draw.vue",
    category: 3002,
  },
  {
    id: "12_编辑图形",
    name: "编辑图形",
    fileName: "openLayersExample/basic/12_编辑图形.vue",
    category: 3002,
  },
  {
    id: "13_平移",
    name: "平移",
    fileName: "openLayersExample/basic/13_平移.vue",
    category: 3002,
  },
  {
    id: "14_Select",
    name: "Select",
    fileName: "openLayersExample/basic/14_Select.vue",
    category: 3002,
  },
  {
    id: "102_绘制",
    name: "绘制",
    fileName: "openLayersExample/basic/102_绘制.vue",
    category: 3002,
  },
  {
    id: "106_测量工具",
    name: "测量工具",
    fileName: "openLayersExample/basic/106_测量工具.vue",
    category: 3002,
  },
  {
    id: "122_长度面积计算",
    name: "长度面积计算",
    fileName: "openLayersExample/basic/122_长度面积计算.vue",
    category: 3007,
  },
  {
    id: "127_导出PNG",
    name: "导出PNG",
    fileName: "openLayersExample/basic/127_导出PNG.vue",
    category: 3002,
  },
  {
    id: "128_图层望远镜",
    name: "图层望远镜",
    fileName: "openLayersExample/basic/128_图层望远镜.vue",
    category: 3002,
  },
  {
    id: "129_图层放大",
    name: "图层放大",
    fileName: "openLayersExample/basic/129_图层放大.vue",
    category: 3002,
  },
  {
    id: "121_即时渲染",
    name: "即时渲染",
    fileName: "openLayersExample/basic/121_即时渲染.vue",
    category: 3002,
  },
  {
    id: "132_共享视图",
    name: "共享视图",
    fileName: "openLayersExample/basic/132_共享视图.vue",
    category: 3002,
  },
  {
    id: "104_热力图",
    name: "热力图",
    fileName: "openLayersExample/basic/104_热力图.vue",
    category: 3003,
  },
  {
    id: "09_热力图",
    name: "热力图(示例2)",
    fileName: "openLayersExample/basic/09_热力图.vue",
    category: 3003,
  },
  {
    id: "101_点位聚合",
    name: "点位聚合",
    fileName: "openLayersExample/basic/101_点位聚合.vue",
    category: 3003,
  },
  {
    id: "108_动态闪烁",
    name: "动态闪烁",
    fileName: "openLayersExample/basic/108_动态闪烁.vue",
    category: 3003,
  },
  {
    id: "109_分屏对比",
    name: "分屏对比",
    fileName: "openLayersExample/basic/109_分屏对比.vue",
    category: 3003,
  },
  {
    id: "110_ol-echarts",
    name: "ol-echarts",
    fileName: "openLayersExample/basic/110_ol-echarts.vue",
    category: 3003,
  },
  {
    id: "105_信息弹窗",
    name: "信息弹窗",
    fileName: "openLayersExample/basic/105_信息弹窗.vue",
    category: 3003,
  },
  {
    id: "119_动态数据",
    name: "动态数据",
    fileName: "openLayersExample/basic/119_动态数据.vue",
    category: 3003,
  },
  {
    id: "131_文本碰撞检测",
    name: "文本碰撞检测",
    fileName: "openLayersExample/basic/131_文本碰撞检测.vue",
    category: 3003,
  },
  {
    id: "133_沿线文本",
    name: "沿线文本",
    fileName: "openLayersExample/basic/133_沿线文本.vue",
    category: 3003,
  },
  {
    id: "134_平滑算法",
    name: "平滑算法",
    fileName: "openLayersExample/basic/134_平滑算法.vue",
    category: 3007,
  },
  {
    id: "130_自定义形状",
    name: "自定义形状",
    fileName: "openLayersExample/basic/130_自定义形状.vue",
    category: 3003,
  },
  {
    id: "120_Style属性调试",
    name: "Style属性调试",
    fileName: "openLayersExample/basic/120_Style属性调试.vue",
    category: 3003,
  },
  {
    id: "117_添加顶点样式",
    name: "添加顶点样式",
    fileName: "openLayersExample/basic/117_添加顶点样式.vue",
    category: 3003,
  },
  {
    id: "118_绘制五角星",
    name: "绘制五角星",
    fileName: "openLayersExample/basic/118_绘制五角星.vue",
    category: 3003,
  },
  {
    id: "103_轨迹回放",
    name: "轨迹回放",
    fileName: "openLayersExample/basic/103_轨迹回放.vue",
    category: 3004,
  },
  {
    id: "135_追踪要素",
    name: "追踪要素",
    fileName: "openLayersExample/basic/135_追踪要素.vue",
    category: 3004,
  },
  {
    id: "125_绘制箭头线",
    name: "绘制箭头线",
    fileName: "openLayersExample/basic/125_绘制箭头线.vue",
    category: 3003,
  },
  {
    id: "115_加载gif图",
    name: "加载gif图",
    fileName: "openLayersExample/basic/115_加载gif图.vue",
    category: 3008,
  },
  {
    id: "02_静态图片_GeoJson",
    name: "静态图片_GeoJson",
    fileName: "openLayersExample/basic/02_静态图片_GeoJson.vue",
    category: 3008,
  },
  {
    id: "03_添加一个点图层",
    name: "添加一个点图层",
    fileName: "openLayersExample/basic/03_添加一个点图层.vue",
    category: 3008,
  },
  {
    id: "04_测试Select",
    name: "测试Select",
    fileName: "openLayersExample/basic/04_测试Select.vue",
    category: 3002,
  },
  {
    id: "136_webgl渲染海量点位",
    name: "webgl渲染海量点位",
    fileName: "openLayersExample/basic/136_webgl渲染海量点位.vue",
    category: 3005,
  },
  {
    id: "137_webgl渲染精灵图",
    name: "webgl渲染精灵图",
    fileName: "openLayersExample/basic/137_webgl渲染精灵图.vue",
    category: 3005,
  },
  {
    id: "139_风场",
    name: "风场",
    fileName: "openLayersExample/basic/139_风场.vue",
    category: 3006,
  },
  {
    id: "138_风箭",
    name: "风箭",
    fileName: "openLayersExample/basic/138_风箭.vue",
    category: 3006,
  },
  {
    id: "114_模拟台风风场",
    name: "模拟台风风场",
    fileName: "openLayersExample/basic/114_模拟台风风场.vue",
    category: 3006,
  },
  {
    id: "107_区域掩膜",
    name: "区域掩膜",
    fileName: "openLayersExample/basic/107_区域掩膜.vue",
    category: 3007,
  },
  {
    id: "107_区域掩膜_UI",
    name: "区域掩膜_UI",
    fileName: "openLayersExample/basic/107_区域掩膜_UI.vue",
    category: 3007,
  },
];

